//CHARACTERS
export const FETCH_CHARS = "FETCH_CHARS";
export const FETCH_CHARS_START = "FETCH_CHARS_START";
export const FETCH_CHARS_SUCCESS = "FETCH_CHARS_SUCCESS";
export const FETCH_CHARS_FAIL = "FETCH_CHARS_FAIL";

export const TOGGLE_ALIVE_CHARS = "TOGGLE_ALIVE_CHARS";
export const UPDATE_SEARCH_INPUT = "UPDATE_SEARCH_INPUT";
export const HANDLE_PAGE_CLICK = "HANDLE_PAGE_CLICK";
